---
- name: Install maven and docker on jenkins-slave
  hosts: jenkins-slave
  become: true 
  tasks: 
  - name: update ubuntu repo and cache 
    apt: 
      update_cache: yes  
      cache_valid_time: 3600 

  - name: install java 
    apt: 
      name: openjdk-17-jre
      state: present
      
  - name: install java 
    apt: 
      name: openjdk-11-jre
      state: present

  - name: download maven packages 
    get_url:
      url: https://dlcdn.apache.org/maven/maven-3/3.9.6/binaries/apache-maven-3.9.6-bin.tar.gz
      dest: /opt

  - name: extract maven packages 
    unarchive:
      src: /opt/apache-maven-3.9.6-bin.tar.gz
      dest: /opt 
      remote_src: yes

  - name: install docker 
    apt: 
      name: docker.io 
      state: present

  - name: start docker services 
    service: 
      name: docker 
      state: started 
  
  - name: give 777 permissions on /var/run/docker.sock
    file: 
      path: /var/run/docker.sock
      state: file 
      mode: 0777

  - name: start docker on boot time 
    service: 
      name: docker 
      enabled: yes 

  - name: Download kubectl binary
    get_url:
      url: "https://s3.us-west-2.amazonaws.com/amazon-eks/1.24.9/2023-01-11/bin/linux/amd64/kubectl"
      dest: "/tmp/kubectl"

  - name: Set execute permission on kubectl binary
    file:
      path: "/tmp/kubectl"
      mode: "u+x"

  - name: Move kubectl binary to /usr/local/bin
    command: mv /tmp/kubectl /usr/local/bin/kubectl

  - name: Install unzip package
    apt:
      name: unzip
      state: present

  - name: Download awscli v2 zip file
    get_url:
      url: "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip"
      dest: "/tmp/awscliv2.zip"

  - name: Unzip awscli v2 zip file
    unarchive:
      src: "/tmp/awscliv2.zip"
      dest: "/tmp/awscliv2"

  - name: Install awscli v2
    command: sudo /tmp/awscliv2/aws/install --update
  
  - name: Download get_helm.sh script
    get_url:
      url: "https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3"
      dest: "/tmp/get_helm.sh"

  - name: Set execute permission on get_helm.sh script
    file:
      path: "/tmp/get_helm.sh"
      mode: "u+x"

  - name: Run get_helm.sh script
    command: "/tmp/get_helm.sh"



      